name: Run tests
on: [push, workflow_dispatch]
jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - "5.4.7" # latest stable
          - "luajit-openresty" # latest openresty luajit (luajit stopped publishing versions)
          - "5.3.6" # Awesome lua version v4.3
          - "5.2.4" # Earliest supported version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - name: test against lua ${{ matrix.luaVersion }}
        run: |
          lua=$(command -v lua 2>/dev/null|| command -v luajit 2>/dev/null)
          "$lua" ./test/init.lua
